---
abstract: 'Gva extension to the prototype javascript framework'
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-GvaScript
provides:
  Alien::GvaScript:
    file: lib/Alien/GvaScript.pm
    version: 1.22
recommends:
  Pod::POM: 0
  Pod::POM::View: 0
  Pod::POM::View::HTML: 0
requires:
  File::Copy: 0
  File::Path: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.22
