---
name: Alien-GvaScript
version: 1.18
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
abstract: Gva extension to the prototype javascript framework
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  File::Copy: 0
  File::Path: 0
recommends:
  Pod::POM: 0
  Pod::POM::View: 0
  Pod::POM::View::HTML: 0
configure_requires:
  Module::Build: 0.35
provides:
  Alien::GvaScript:
    file: lib/Alien/GvaScript.pm
    version: 1.18
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
